/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Cliente;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClienteApiServiceApi
 */
@Disabled
public class ClienteApiServiceApiTest {

    private final ClienteApiServiceApi api = new ClienteApiServiceApi();

    /**
     * Actualiza un cliente existente
     *
     * Permite actualizar un cliente
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void actualizarClienteTest() throws ApiException {
        Cliente cliente = null;
        Cliente response = api.actualizarCliente(cliente);
        // TODO: test validations
    }

    /**
     * Consulta de cliente por dni
     *
     * Permite obetner un cliente por su dni
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarClientPorDniTest() throws ApiException {
        String dni = null;
        Cliente response = api.consultarClientPorDni(dni);
        // TODO: test validations
    }

    /**
     * Consulta de cliente por id
     *
     * Permite obetner un cliente por su id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarClientePorIdTest() throws ApiException {
        String id = null;
        Cliente response = api.consultarClientePorId(id);
        // TODO: test validations
    }

    /**
     * Crear un cliente nuevo
     *
     * Permite crear un cliente
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void crearClienteTest() throws ApiException {
        Cliente cliente = null;
        Cliente response = api.crearCliente(cliente);
        // TODO: test validations
    }

}
