/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.time.LocalDate;
import org.openapitools.client.model.Pedido;
import org.openapitools.client.model.PedidoDetalle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PedidoApiServiceApi
 */
@Disabled
public class PedidoApiServiceApiTest {

    private final PedidoApiServiceApi api = new PedidoApiServiceApi();

    /**
     * Añadir detalle pedido
     *
     * Permite añadir detalle de pedido a un pedido
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void aadirDetallePedidoTest() throws ApiException {
        String id = null;
        PedidoDetalle pedidoDetalle = null;
        Pedido response = api.aadirDetallePedido(id, pedidoDetalle);
        // TODO: test validations
    }

    /**
     * Consulta lista pedidos por dos fechas
     *
     * Consulta una lista de pedidos entre dos fechas
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void buscarPedidosEntreFechasTest() throws ApiException {
        LocalDate fecha1 = null;
        LocalDate fecha2 = null;
        List<Pedido> response = api.buscarPedidosEntreFechas(fecha1, fecha2);
        // TODO: test validations
    }

    /**
     * Consulta pedido por id
     *
     * Consulta un pedido mediante una id y lo devuelve
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarPedidoTest() throws ApiException {
        String id = null;
        Pedido response = api.consultarPedido(id);
        // TODO: test validations
    }

    /**
     * Consulta lista pedidos por dni
     *
     * Consulta una lista de pedido mediante un dni del cliente
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarPedidoClienteTest() throws ApiException {
        String dni = null;
        List<Pedido> response = api.consultarPedidoCliente(dni);
        // TODO: test validations
    }

    /**
     * Registrar pedido nuevo
     *
     * Permite registrar un nuevo pedido completo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registrarPedidoTest() throws ApiException {
        Pedido pedido = null;
        String response = api.registrarPedido(pedido);
        // TODO: test validations
    }

}
