/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ceu.dam.ad.api.user.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import ceu.dam.ad.api.user.client.JSON;

import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * CambiarPasswordRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-30T16:38:00.315918200+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class CambiarPasswordRequest {
  public static final String SERIALIZED_NAME_OLD_PASS = "oldPass";
  @SerializedName(SERIALIZED_NAME_OLD_PASS)
  @javax.annotation.Nonnull
  private String oldPass;

  public static final String SERIALIZED_NAME_NEW_PASS = "newPass";
  @SerializedName(SERIALIZED_NAME_NEW_PASS)
  @javax.annotation.Nonnull
  private String newPass;

  public CambiarPasswordRequest() {
  }

  public CambiarPasswordRequest oldPass(@javax.annotation.Nonnull String oldPass) {
    this.oldPass = oldPass;
    return this;
  }

  /**
   * Get oldPass
   * @return oldPass
   */
  @javax.annotation.Nonnull
  public String getOldPass() {
    return oldPass;
  }

  public void setOldPass(@javax.annotation.Nonnull String oldPass) {
    this.oldPass = oldPass;
  }


  public CambiarPasswordRequest newPass(@javax.annotation.Nonnull String newPass) {
    this.newPass = newPass;
    return this;
  }

  /**
   * Get newPass
   * @return newPass
   */
  @javax.annotation.Nonnull
  public String getNewPass() {
    return newPass;
  }

  public void setNewPass(@javax.annotation.Nonnull String newPass) {
    this.newPass = newPass;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CambiarPasswordRequest cambiarPasswordRequest = (CambiarPasswordRequest) o;
    return Objects.equals(this.oldPass, cambiarPasswordRequest.oldPass) &&
        Objects.equals(this.newPass, cambiarPasswordRequest.newPass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldPass, newPass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CambiarPasswordRequest {\n");
    sb.append("    oldPass: ").append(toIndentedString(oldPass)).append("\n");
    sb.append("    newPass: ").append(toIndentedString(newPass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("oldPass");
    openapiFields.add("newPass");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("oldPass");
    openapiRequiredFields.add("newPass");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CambiarPasswordRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CambiarPasswordRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CambiarPasswordRequest is not found in the empty JSON string", CambiarPasswordRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CambiarPasswordRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CambiarPasswordRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CambiarPasswordRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("oldPass").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `oldPass` to be a primitive type in the JSON string but got `%s`", jsonObj.get("oldPass").toString()));
      }
      if (!jsonObj.get("newPass").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newPass` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newPass").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CambiarPasswordRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CambiarPasswordRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CambiarPasswordRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CambiarPasswordRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CambiarPasswordRequest>() {
           @Override
           public void write(JsonWriter out, CambiarPasswordRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CambiarPasswordRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CambiarPasswordRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CambiarPasswordRequest
   * @throws IOException if the JSON string is invalid with respect to CambiarPasswordRequest
   */
  public static CambiarPasswordRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CambiarPasswordRequest.class);
  }

  /**
   * Convert an instance of CambiarPasswordRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

