/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import ceu.dam.ad.api.user.client.model.CambiarPasswordRequest;

import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CambiarPasswordRequest
 */
public class CambiarPasswordRequestTest {
    private final CambiarPasswordRequest model = new CambiarPasswordRequest();

    /**
     * Model tests for CambiarPasswordRequest
     */
    @Test
    public void testCambiarPasswordRequest() {
        // TODO: test CambiarPasswordRequest
    }

    /**
     * Test the property 'oldPass'
     */
    @Test
    public void oldPassTest() {
        // TODO: test oldPass
    }

    /**
     * Test the property 'newPass'
     */
    @Test
    public void newPassTest() {
        // TODO: test newPass
    }

}
