/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import ceu.dam.ad.api.user.client.ApiException;
import ceu.dam.ad.api.user.client.api.UserApiApi;
import ceu.dam.ad.api.user.client.model.CambiarPasswordRequest;
import ceu.dam.ad.api.user.client.model.CreateUserRequest;
import ceu.dam.ad.api.user.client.model.User;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApiApi
 */
@Disabled
public class UserApiApiTest {

    private final UserApiApi api = new UserApiApi();

    /**
     * Cambiar contraseña
     *
     * Permite cambiar la contraseña del usuario pasandole su id, antigua y nueva contraseña
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cambiarPasswordTest() throws ApiException {
        Long idUser = null;
        CambiarPasswordRequest cambiarPasswordRequest = null;
        api.cambiarPassword(idUser, cambiarPasswordRequest);
        // TODO: test validations
    }

    /**
     * Consulta un usario
     *
     * Permite consultar un usuario mediante una id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void consultarUserTest() throws ApiException {
        Long id = null;
        User response = api.consultarUser(id);
        // TODO: test validations
    }

    /**
     * Crear un nuevo usuario
     *
     * Permite crear un nuevo usuario
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void crearUsarioTest() throws ApiException {
        CreateUserRequest createUserRequest = null;
        User response = api.crearUsario(createUserRequest);
        // TODO: test validations
    }

    /**
     * Iniciar sesion 
     *
     * Permite iniciar sesion medienate un usuario y un password
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void inicarSesionTest() throws ApiException {
        String login = null;
        String password = null;
        User response = api.inicarSesion(login, password);
        // TODO: test validations
    }

}
